"""
    Yieldster SDK API

    Swagger documentation for Yieldster 2.0 SDK API's  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import JavaApi.openapi_client
from JavaApi.openapi_client.model.ui_response import UIResponse


class TestUIResponse(unittest.TestCase):
    """UIResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUIResponse(self):
        """Test UIResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
