"""
    Yieldster SDK API

    Swagger documentation for Yieldster 2.0 SDK API's  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import JavaApi.openapi_client
from JavaApi.openapi_client.api.add_asset_service_api import ADDASSETSERVICEApi  # noqa: E501


class TestADDASSETSERVICEApi(unittest.TestCase):
    """ADDASSETSERVICEApi unit test stubs"""

    def setUp(self):
        self.api = ADDASSETSERVICEApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_icons(self):
        """Test case for add_icons

        API to add assets images from a file  # noqa: E501
        """
        pass

    def test_get_all_assets(self):
        """Test case for get_all_assets

        API to fetch all assets  # noqa: E501
        """
        pass

    def test_get_asset_by_name(self):
        """Test case for get_asset_by_name

        API to get asset by name  # noqa: E501
        """
        pass

    def test_get_asset_by_symbol(self):
        """Test case for get_asset_by_symbol

        API to get asset by Symbol  # noqa: E501
        """
        pass

    def test_get_protocol_by_id1(self):
        """Test case for get_protocol_by_id1

        API to get Asset By ID  # noqa: E501
        """
        pass

    def test_remove_protocol1(self):
        """Test case for remove_protocol1

        API to DELETE_ASSET By Id  # noqa: E501
        """
        pass

    def test_update_vault1(self):
        """Test case for update_vault1

        API to update asset details by Id   # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
