"""
    Yieldster SDK API

    Swagger documentation for Yieldster 2.0 SDK API's  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import JavaApi.openapi_client
from JavaApi.openapi_client.api.deposit_strategy_service_api import DEPOSITSTRATEGYSERVICEApi  # noqa: E501


class TestDEPOSITSTRATEGYSERVICEApi(unittest.TestCase):
    """DEPOSITSTRATEGYSERVICEApi unit test stubs"""

    def setUp(self):
        self.api = DEPOSITSTRATEGYSERVICEApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_deposit_strategy(self):
        """Test case for add_deposit_strategy

        API to add deposit strategy  # noqa: E501
        """
        pass

    def test_get_all_deposit_strategy(self):
        """Test case for get_all_deposit_strategy

        API to get all Deposit Strategy details  # noqa: E501
        """
        pass

    def test_get_deposit_strategy_by_id(self):
        """Test case for get_deposit_strategy_by_id

        API to get deposit strategy details by ID   # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
