"""
    Yieldster SDK API

    Swagger documentation for Yieldster 2.0 SDK API's  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import JavaApi.openapi_client
from JavaApi.openapi_client.api.sdk_service_api import SDKSERVICEApi  # noqa: E501


class TestSDKSERVICEApi(unittest.TestCase):
    """SDKSERVICEApi unit test stubs"""

    def setUp(self):
        self.api = SDKSERVICEApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_token_balance(self):
        """Test case for get_token_balance

        API to get Historical Token Balance of Vault  # noqa: E501
        """
        pass

    def test_get_token_price(self):
        """Test case for get_token_price

        API to get Historical Token Price of Vault  # noqa: E501
        """
        pass

    def test_get_vault_assets(self):
        """Test case for get_vault_assets

        API to get Assets of a vault  # noqa: E501
        """
        pass

    def test_get_vault_nav(self):
        """Test case for get_vault_nav

        API to get Historical NAV of a vault  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
