"""
    Yieldster SDK API

    Swagger documentation for Yieldster 2.0 SDK API's  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import JavaApi.openapi_client
from JavaApi.openapi_client.model.sdk_response import SDKResponse


class TestSDKResponse(unittest.TestCase):
    """SDKResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSDKResponse(self):
        """Test SDKResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SDKResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
