"""
    Yieldster SDK API

    Swagger documentation for Yieldster 2.0 SDK API's  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import JavaApi.openapi_client
from JavaApi.openapi_client.model.eth_transaction import EthTransaction
globals()['EthTransaction'] = EthTransaction
from JavaApi.openapi_client.model.pending_vault_transaction import PendingVaultTransaction


class TestPendingVaultTransaction(unittest.TestCase):
    """PendingVaultTransaction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPendingVaultTransaction(self):
        """Test PendingVaultTransaction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PendingVaultTransaction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
