"""
    Yieldster SDK API

    Swagger documentation for Yieldster 2.0 SDK API's  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import JavaApi.openapi_client
from JavaApi.openapi_client.api.add_transaction_details_service_api import ADDTRANSACTIONDETAILSSERVICEApi  # noqa: E501


class TestADDTRANSACTIONDETAILSSERVICEApi(unittest.TestCase):
    """ADDTRANSACTIONDETAILSSERVICEApi unit test stubs"""

    def setUp(self):
        self.api = ADDTRANSACTIONDETAILSSERVICEApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_by_transaction_hash(self):
        """Test case for delete_by_transaction_hash

        API to delete transaction details by transaction hash  # noqa: E501
        """
        pass

    def test_get_advisor_transactions(self):
        """Test case for get_advisor_transactions

        API to get advisor transactions by vault address  # noqa: E501
        """
        pass

    def test_get_transaction_by_status(self):
        """Test case for get_transaction_by_status

        API to filter transactions that are not DEPOSIT or WITHDRAWAL  # noqa: E501
        """
        pass

    def test_get_transaction_details_by_hash(self):
        """Test case for get_transaction_details_by_hash

        API to get transaction details using transaction hash  # noqa: E501
        """
        pass

    def test_get_transaction_details_by_type(self):
        """Test case for get_transaction_details_by_type

        API to get transaction details using vault address  # noqa: E501
        """
        pass

    def test_set_transaction_details(self):
        """Test case for set_transaction_details

        API to save transaction details  # noqa: E501
        """
        pass

    def test_transaction_scheduler(self):
        """Test case for transaction_scheduler

        API to update transaction details  # noqa: E501
        """
        pass

    def test_update_temporary_transaction_hash(self):
        """Test case for update_temporary_transaction_hash

        API to update temporary transaction hash  # noqa: E501
        """
        pass

    def test_update_transaction_hash(self):
        """Test case for update_transaction_hash

        API to update transaction hash  # noqa: E501
        """
        pass

    def test_update_transaction_status(self):
        """Test case for update_transaction_status

        API to update transaction status  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
