"""
    Yieldster SDK API

    Swagger documentation for Yieldster 2.0 SDK API's  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import JavaApi.openapi_client
from JavaApi.openapi_client.api.user_controller_api import UserControllerApi  # noqa: E501


class TestUserControllerApi(unittest.TestCase):
    """UserControllerApi unit test stubs"""

    def setUp(self):
        self.api = UserControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_user(self):
        """Test case for add_user

        API to add user details  # noqa: E501
        """
        pass

    def test_get_all_users(self):
        """Test case for get_all_users

        API to get all User  # noqa: E501
        """
        pass

    def test_get_vault_by_financial_details(self):
        """Test case for get_vault_by_financial_details

        API to get Investment Details like TOTAL_BALANCE and TOTAL_RETURN for NAV BAR  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
