"""
    Yieldster SDK API

    Swagger documentation for Yieldster 2.0 SDK API's  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import JavaApi.openapi_client
from JavaApi.openapi_client.api.advisor_controller_api import AdvisorControllerApi  # noqa: E501


class TestAdvisorControllerApi(unittest.TestCase):
    """AdvisorControllerApi unit test stubs"""

    def setUp(self):
        self.api = AdvisorControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_advisorkey(self):
        """Test case for add_advisorkey

        API to get Add Key   # noqa: E501
        """
        pass

    def test_get_advisor_by_id(self):
        """Test case for get_advisor_by_id

        API to get Advisor by ID  # noqa: E501
        """
        pass

    def test_get_all_advisor_keys(self):
        """Test case for get_all_advisor_keys

        API to get ALL_KEYS   # noqa: E501
        """
        pass

    def test_get_all_advisors(self):
        """Test case for get_all_advisors

        API to get ALL_ADVISORS   # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
