"""
    Yieldster SDK API

    Swagger documentation for Yieldster 2.0 SDK API's  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import JavaApi.openapi_client
from JavaApi.openapi_client.api.swagger_2_controller_web_mvc_api import Swagger2ControllerWebMvcApi  # noqa: E501


class TestSwagger2ControllerWebMvcApi(unittest.TestCase):
    """Swagger2ControllerWebMvcApi unit test stubs"""

    def setUp(self):
        self.api = Swagger2ControllerWebMvcApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_documentation(self):
        """Test case for get_documentation

        """
        pass


if __name__ == '__main__':
    unittest.main()
