"""
    Yieldster SDK API

    Swagger documentation for Yieldster 2.0 SDK API's  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import JavaApi.openapi_client
from JavaApi.openapi_client.model.sdk_response import SDKResponse
from JavaApi.openapi_client.model.vault import Vault
globals()['SDKResponse'] = SDKResponse
globals()['Vault'] = Vault
from JavaApi.openapi_client.model.vault_display_model import VaultDisplayModel


class TestVaultDisplayModel(unittest.TestCase):
    """VaultDisplayModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVaultDisplayModel(self):
        """Test VaultDisplayModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VaultDisplayModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
