"""
    Yieldster SDK API

    Swagger documentation for Yieldster 2.0 SDK API's  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import JavaApi.openapi_client
from JavaApi.openapi_client.api.harvest_execution_service_api import HARVESTEXECUTIONSERVICEApi  # noqa: E501


class TestHARVESTEXECUTIONSERVICEApi(unittest.TestCase):
    """HARVESTEXECUTIONSERVICEApi unit test stubs"""

    def setUp(self):
        self.api = HARVESTEXECUTIONSERVICEApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_staking_contract(self):
        """Test case for add_staking_contract

        API to add staking contracts and their respective rewards from file  # noqa: E501
        """
        pass

    def test_add_staking_contract_and_reward(self):
        """Test case for add_staking_contract_and_reward

        API to add address of staking contract and its rewards  # noqa: E501
        """
        pass

    def test_delete_staking_contract(self):
        """Test case for delete_staking_contract

        API to get delete staking contract by address  # noqa: E501
        """
        pass

    def test_get(self):
        """Test case for get

        API to get  keys  # noqa: E501
        """
        pass

    def test_get_reward_amount(self):
        """Test case for get_reward_amount

        API to get amount of rewards of a particular contract for a vault  # noqa: E501
        """
        pass

    def test_get_reward_contract(self):
        """Test case for get_reward_contract

        API to get address of rewards of a particular staking contract  # noqa: E501
        """
        pass

    def test_harvest_reward(self):
        """Test case for harvest_reward

        API to harvest rewards of a particular contract for a vault  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
