"""
    Yieldster SDK API

    Swagger documentation for Yieldster 2.0 SDK API's  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import JavaApi.openapi_client
from JavaApi.openapi_client.model.binary import Binary
globals()['Binary'] = Binary
from JavaApi.openapi_client.model.vault import Vault


class TestVault(unittest.TestCase):
    """Vault unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVault(self):
        """Test Vault"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Vault()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
