"""
    Yieldster SDK API

    Swagger documentation for Yieldster 2.0 SDK API's  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import JavaApi.openapi_client
from JavaApi.openapi_client.api.management_service_api import ManagementServiceApi  # noqa: E501


class TestManagementServiceApi(unittest.TestCase):
    """ManagementServiceApi unit test stubs"""

    def setUp(self):
        self.api = ManagementServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_fee_list1(self):
        """Test case for add_fee_list1

        API to add fee strategy  # noqa: E501
        """
        pass

    def test_get_all_fee_details(self):
        """Test case for get_all_fee_details

        API to fetch fee details  # noqa: E501
        """
        pass

    def test_get_fee_strategy_by_id1(self):
        """Test case for get_fee_strategy_by_id1

        API to get fee strategy details by ID   # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
