"""
    Yieldster SDK API

    Swagger documentation for Yieldster 2.0 SDK API's  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import JavaApi.openapi_client
from JavaApi.openapi_client.api.strategy_controller_api import StrategyControllerApi  # noqa: E501


class TestStrategyControllerApi(unittest.TestCase):
    """StrategyControllerApi unit test stubs"""

    def setUp(self):
        self.api = StrategyControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_strategies(self):
        """Test case for get_all_strategies

        API to get all strategy details  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
