"""
    Yieldster SDK API

    Swagger documentation for Yieldster 2.0 SDK API's  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import JavaApi.openapi_client
from JavaApi.openapi_client.api.protocol_controller_api import ProtocolControllerApi  # noqa: E501


class TestProtocolControllerApi(unittest.TestCase):
    """ProtocolControllerApi unit test stubs"""

    def setUp(self):
        self.api = ProtocolControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_protocol(self):
        """Test case for create_protocol

        API to CREATE_PROTOCOL  # noqa: E501
        """
        pass

    def test_get_all_protocols(self):
        """Test case for get_all_protocols

        API to get ALL_PROTOCOLS  # noqa: E501
        """
        pass

    def test_get_protocol_by_address(self):
        """Test case for get_protocol_by_address

        API to get PROTOCOL_BY_ADDRESS  # noqa: E501
        """
        pass

    def test_get_protocol_by_id(self):
        """Test case for get_protocol_by_id

        API to get Protocol By ID  # noqa: E501
        """
        pass

    def test_remove_protocol(self):
        """Test case for remove_protocol

        API to DELETE_PROTOCOL By Id  # noqa: E501
        """
        pass

    def test_update_vault(self):
        """Test case for update_vault

        API to update protocol details by Id   # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
