"""
    Yieldster SDK API

    Swagger documentation for Yieldster 2.0 SDK API's  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from JavaApi.openapi_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from JavaApi.openapi_client.exceptions import ApiAttributeError


def lazy_import():
    from JavaApi.openapi_client.model.access_list_object import AccessListObject
    globals()['AccessListObject'] = AccessListObject


class Transaction(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'hash': (str,),  # noqa: E501
            'nonce': (int,),  # noqa: E501
            'block_hash': (str,),  # noqa: E501
            'block_number': (int,),  # noqa: E501
            'chain_id': (int,),  # noqa: E501
            'transaction_index': (int,),  # noqa: E501
            '_from': (str,),  # noqa: E501
            'to': (str,),  # noqa: E501
            'value': (int,),  # noqa: E501
            'gas_price': (int,),  # noqa: E501
            'gas': (int,),  # noqa: E501
            'input': (str,),  # noqa: E501
            'creates': (str,),  # noqa: E501
            'public_key': (str,),  # noqa: E501
            'raw': (str,),  # noqa: E501
            'r': (str,),  # noqa: E501
            's': (str,),  # noqa: E501
            'v': (int,),  # noqa: E501
            'type': (str,),  # noqa: E501
            'max_fee_per_gas': (int,),  # noqa: E501
            'max_priority_fee_per_gas': (int,),  # noqa: E501
            'access_list': ([AccessListObject],),  # noqa: E501
            'nonce_raw': (str,),  # noqa: E501
            'block_number_raw': (str,),  # noqa: E501
            'transaction_index_raw': (str,),  # noqa: E501
            'value_raw': (str,),  # noqa: E501
            'gas_price_raw': (str,),  # noqa: E501
            'gas_raw': (str,),  # noqa: E501
            'chain_id_raw': (str,),  # noqa: E501
            'max_fee_per_gas_raw': (str,),  # noqa: E501
            'max_priority_fee_per_gas_raw': (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'hash': 'hash',  # noqa: E501
        'nonce': 'nonce',  # noqa: E501
        'block_hash': 'blockHash',  # noqa: E501
        'block_number': 'blockNumber',  # noqa: E501
        'chain_id': 'chainId',  # noqa: E501
        'transaction_index': 'transactionIndex',  # noqa: E501
        '_from': 'from',  # noqa: E501
        'to': 'to',  # noqa: E501
        'value': 'value',  # noqa: E501
        'gas_price': 'gasPrice',  # noqa: E501
        'gas': 'gas',  # noqa: E501
        'input': 'input',  # noqa: E501
        'creates': 'creates',  # noqa: E501
        'public_key': 'publicKey',  # noqa: E501
        'raw': 'raw',  # noqa: E501
        'r': 'r',  # noqa: E501
        's': 's',  # noqa: E501
        'v': 'v',  # noqa: E501
        'type': 'type',  # noqa: E501
        'max_fee_per_gas': 'maxFeePerGas',  # noqa: E501
        'max_priority_fee_per_gas': 'maxPriorityFeePerGas',  # noqa: E501
        'access_list': 'accessList',  # noqa: E501
        'nonce_raw': 'nonceRaw',  # noqa: E501
        'block_number_raw': 'blockNumberRaw',  # noqa: E501
        'transaction_index_raw': 'transactionIndexRaw',  # noqa: E501
        'value_raw': 'valueRaw',  # noqa: E501
        'gas_price_raw': 'gasPriceRaw',  # noqa: E501
        'gas_raw': 'gasRaw',  # noqa: E501
        'chain_id_raw': 'chainIdRaw',  # noqa: E501
        'max_fee_per_gas_raw': 'maxFeePerGasRaw',  # noqa: E501
        'max_priority_fee_per_gas_raw': 'maxPriorityFeePerGasRaw',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """Transaction - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            hash (str): [optional]  # noqa: E501
            nonce (int): [optional]  # noqa: E501
            block_hash (str): [optional]  # noqa: E501
            block_number (int): [optional]  # noqa: E501
            chain_id (int): [optional]  # noqa: E501
            transaction_index (int): [optional]  # noqa: E501
            _from (str): [optional]  # noqa: E501
            to (str): [optional]  # noqa: E501
            value (int): [optional]  # noqa: E501
            gas_price (int): [optional]  # noqa: E501
            gas (int): [optional]  # noqa: E501
            input (str): [optional]  # noqa: E501
            creates (str): [optional]  # noqa: E501
            public_key (str): [optional]  # noqa: E501
            raw (str): [optional]  # noqa: E501
            r (str): [optional]  # noqa: E501
            s (str): [optional]  # noqa: E501
            v (int): [optional]  # noqa: E501
            type (str): [optional]  # noqa: E501
            max_fee_per_gas (int): [optional]  # noqa: E501
            max_priority_fee_per_gas (int): [optional]  # noqa: E501
            access_list ([AccessListObject]): [optional]  # noqa: E501
            nonce_raw (str): [optional]  # noqa: E501
            block_number_raw (str): [optional]  # noqa: E501
            transaction_index_raw (str): [optional]  # noqa: E501
            value_raw (str): [optional]  # noqa: E501
            gas_price_raw (str): [optional]  # noqa: E501
            gas_raw (str): [optional]  # noqa: E501
            chain_id_raw (str): [optional]  # noqa: E501
            max_fee_per_gas_raw (str): [optional]  # noqa: E501
            max_priority_fee_per_gas_raw (str): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """Transaction - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            hash (str): [optional]  # noqa: E501
            nonce (int): [optional]  # noqa: E501
            block_hash (str): [optional]  # noqa: E501
            block_number (int): [optional]  # noqa: E501
            chain_id (int): [optional]  # noqa: E501
            transaction_index (int): [optional]  # noqa: E501
            _from (str): [optional]  # noqa: E501
            to (str): [optional]  # noqa: E501
            value (int): [optional]  # noqa: E501
            gas_price (int): [optional]  # noqa: E501
            gas (int): [optional]  # noqa: E501
            input (str): [optional]  # noqa: E501
            creates (str): [optional]  # noqa: E501
            public_key (str): [optional]  # noqa: E501
            raw (str): [optional]  # noqa: E501
            r (str): [optional]  # noqa: E501
            s (str): [optional]  # noqa: E501
            v (int): [optional]  # noqa: E501
            type (str): [optional]  # noqa: E501
            max_fee_per_gas (int): [optional]  # noqa: E501
            max_priority_fee_per_gas (int): [optional]  # noqa: E501
            access_list ([AccessListObject]): [optional]  # noqa: E501
            nonce_raw (str): [optional]  # noqa: E501
            block_number_raw (str): [optional]  # noqa: E501
            transaction_index_raw (str): [optional]  # noqa: E501
            value_raw (str): [optional]  # noqa: E501
            gas_price_raw (str): [optional]  # noqa: E501
            gas_raw (str): [optional]  # noqa: E501
            chain_id_raw (str): [optional]  # noqa: E501
            max_fee_per_gas_raw (str): [optional]  # noqa: E501
            max_priority_fee_per_gas_raw (str): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
