"""
    Yieldster SDK API

    Swagger documentation for Yieldster 2.0 SDK API's  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import YieldsterSDK.openapi_client
from YieldsterSDK.openapi_client.api.withdraw_strategy_service_api import WithdrawStrategyServiceApi  # noqa: E501


class TestWithdrawStrategyServiceApi(unittest.TestCase):
    """WithdrawStrategyServiceApi unit test stubs"""

    def setUp(self):
        self.api = WithdrawStrategyServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_fee_list(self):
        """Test case for add_fee_list

        API to add withdraw strategy  # noqa: E501
        """
        pass

    def test_get_all_withdraw_strategy(self):
        """Test case for get_all_withdraw_strategy

        API to get all withdraw Strategy details  # noqa: E501
        """
        pass

    def test_get_fee_strategy_by_id(self):
        """Test case for get_fee_strategy_by_id

        API to get withdrawal strategy details by ID   # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
