"""
    Yieldster SDK API

    Swagger documentation for Yieldster 2.0 SDK API's  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import YieldsterSDK.openapi_client
from YieldsterSDK.openapi_client.api.vault_service_api import VAULTSERVICEApi  # noqa: E501


class TestVAULTSERVICEApi(unittest.TestCase):
    """VAULTSERVICEApi unit test stubs"""

    def setUp(self):
        self.api = VAULTSERVICEApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_staked_pools(self):
        """Test case for add_staked_pools

        API to add staked pools of a vault  # noqa: E501
        """
        pass

    def test_edge_activator(self):
        """Test case for edge_activator

        """
        pass

    def test_execute_withdraw(self):
        """Test case for execute_withdraw

        API to execute a withdraw from a vault  # noqa: E501
        """
        pass

    def test_featured_status(self):
        """Test case for featured_status

        API to update featured Vault by Id   # noqa: E501
        """
        pass

    def test_get_advisor_details(self):
        """Test case for get_advisor_details

        API to get advisor details of a vault  # noqa: E501
        """
        pass

    def test_get_advisor_setting_by_vault_id(self):
        """Test case for get_advisor_setting_by_vault_id

        API to get VAULT_ADVISOR_SETTINGS   # noqa: E501
        """
        pass

    def test_get_all_my_vaults(self):
        """Test case for get_all_my_vaults

        API to get MY_VAULTS by pagination  # noqa: E501
        """
        pass

    def test_get_all_vaults(self):
        """Test case for get_all_vaults

        API to get all vault details  # noqa: E501
        """
        pass

    def test_get_all_vaults_by_pagination(self):
        """Test case for get_all_vaults_by_pagination

        API to get ALL_VAULTS By Paginating  # noqa: E501
        """
        pass

    def test_get_apr(self):
        """Test case for get_apr

        API to get APR   # noqa: E501
        """
        pass

    def test_get_asset_by_vault_id(self):
        """Test case for get_asset_by_vault_id

        API to get asset details of a vault  # noqa: E501
        """
        pass

    def test_get_dashboard_graph(self):
        """Test case for get_dashboard_graph

        """
        pass

    def test_get_details_by_search(self):
        """Test case for get_details_by_search

        API to get asset, protocol and vault details by SEARCHING  # noqa: E501
        """
        pass

    def test_get_details_for_auto_complete(self):
        """Test case for get_details_for_auto_complete

        API to achieve AUTO_COMPLETE on the basis of protocols, assets and vaults  # noqa: E501
        """
        pass

    def test_get_featured_vault_details_by_pagination(self):
        """Test case for get_featured_vault_details_by_pagination

        API to get FEATURED_VAULTS by pagination  # noqa: E501
        """
        pass

    def test_get_fee_summary(self):
        """Test case for get_fee_summary

        """
        pass

    def test_get_gas_estimate(self):
        """Test case for get_gas_estimate

        API to get gas estimate for a particular transaction  # noqa: E501
        """
        pass

    def test_get_invested_protocol_by_vault_id(self):
        """Test case for get_invested_protocol_by_vault_id

        API to get invested protocol of a vault  # noqa: E501
        """
        pass

    def test_get_nav_and_liquidated_value(self):
        """Test case for get_nav_and_liquidated_value

        API to get NAV and Liquidated value  # noqa: E501
        """
        pass

    def test_get_protocols_by_vault_id(self):
        """Test case for get_protocols_by_vault_id

        API to get supported protocols of a vault  # noqa: E501
        """
        pass

    def test_get_public_vaults(self):
        """Test case for get_public_vaults

        API to list all public vaults  # noqa: E501
        """
        pass

    def test_get_staked_pools(self):
        """Test case for get_staked_pools

        API to get staked pools of a vault  # noqa: E501
        """
        pass

    def test_get_vault_asset_listwith_historical_data(self):
        """Test case for get_vault_asset_listwith_historical_data

        API to filter vault assetList along with historical Data   # noqa: E501
        """
        pass

    def test_get_vault_by_address(self):
        """Test case for get_vault_by_address

        API to get VaultByAddress  # noqa: E501
        """
        pass

    def test_get_vault_by_base_currency(self):
        """Test case for get_vault_by_base_currency

        API to get VAULT_BY_BASE_CURRENCY  # noqa: E501
        """
        pass

    def test_get_vault_by_financial_details1(self):
        """Test case for get_vault_by_financial_details1

        API to get Investment Details like TOTAL_BALANCE and TOTAL_RETURN for NAV BAR  # noqa: E501
        """
        pass

    def test_get_vault_by_id(self):
        """Test case for get_vault_by_id

        API to get vault details by ID   # noqa: E501
        """
        pass

    def test_get_vault_by_id1(self):
        """Test case for get_vault_by_id1

        API to get vault token details of user and Token Nav   # noqa: E501
        """
        pass

    def test_get_vault_by_vault_address(self):
        """Test case for get_vault_by_vault_address

        API to get deposit and withdrawal strategy by Vault Address   # noqa: E501
        """
        pass

    def test_get_vault_details(self):
        """Test case for get_vault_details

        """
        pass

    def test_get_vault_details_by_filtering_with_pagination(self):
        """Test case for get_vault_details_by_filtering_with_pagination

        API to get VAULT_BY_FILTERING  # noqa: E501
        """
        pass

    def test_get_vault_image(self):
        """Test case for get_vault_image

        API to get VAULT_ICON  # noqa: E501
        """
        pass

    def test_get_vault_sorted(self):
        """Test case for get_vault_sorted

        API to get SORTED_VAULTS  # noqa: E501
        """
        pass

    def test_get_vault_transaction_by_vault_address_and_pending_or_reverted(self):
        """Test case for get_vault_transaction_by_vault_address_and_pending_or_reverted

        API to filter vault transaction by txStatus (PENDING/REVERTED)   # noqa: E501
        """
        pass

    def test_get_whitelist_details(self):
        """Test case for get_whitelist_details

        API to get whitelist details of a vault  # noqa: E501
        """
        pass

    def test_profit_management_fee(self):
        """Test case for profit_management_fee

        API to update PROFIT MANAGEMENT FEE   # noqa: E501
        """
        pass

    def test_switch_vault_to_private(self):
        """Test case for switch_vault_to_private

        API to  switch vault to private.  # noqa: E501
        """
        pass

    def test_switch_vault_to_public(self):
        """Test case for switch_vault_to_public

        API to  switch vault to public.  # noqa: E501
        """
        pass

    def test_update_advisor_config(self):
        """Test case for update_advisor_config

        API to update advisor configuration of vault  # noqa: E501
        """
        pass

    def test_update_asset_list(self):
        """Test case for update_asset_list

        API to update Supported AssetList in a vault  # noqa: E501
        """
        pass

    def test_update_deposit_strategy(self):
        """Test case for update_deposit_strategy

        API to update deposit strategy of a vault  # noqa: E501
        """
        pass

    def test_update_emergency_vault_address(self):
        """Test case for update_emergency_vault_address

        API to update emergency vault address   # noqa: E501
        """
        pass

    def test_update_management_fee_percentage_and_beneficiary(self):
        """Test case for update_management_fee_percentage_and_beneficiary

        API to update managementFee Percentage and Beneficiary   # noqa: E501
        """
        pass

    def test_update_protocol_list(self):
        """Test case for update_protocol_list

        API to update Supported ProtocolList in a vault  # noqa: E501
        """
        pass

    def test_update_supported_assets(self):
        """Test case for update_supported_assets

        API to update supported assets of vault  # noqa: E501
        """
        pass

    def test_update_supported_protocols(self):
        """Test case for update_supported_protocols

        API to update supported protocols of vault  # noqa: E501
        """
        pass

    def test_update_supported_vaults(self):
        """Test case for update_supported_vaults

        API to update supported vaults  # noqa: E501
        """
        pass

    def test_update_vault_admin(self):
        """Test case for update_vault_admin

        API to update vault admin   # noqa: E501
        """
        pass

    def test_update_vault_name(self):
        """Test case for update_vault_name

        API to update vault name   # noqa: E501
        """
        pass

    def test_update_vault_visibility(self):
        """Test case for update_vault_visibility

        API to update vault visibility   # noqa: E501
        """
        pass

    def test_update_withdrawal_strategy(self):
        """Test case for update_withdrawal_strategy

        API to update withdrawal strategy of vault  # noqa: E501
        """
        pass

    def test_user_investment_details(self):
        """Test case for user_investment_details

        """
        pass


if __name__ == '__main__':
    unittest.main()
