"""
    Yieldster SDK API

    Swagger documentation for Yieldster 2.0 SDK API's  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import YieldsterSDK.openapi_client
from YieldsterSDK.openapi_client.api.erc_20_transaction_controller_api import Erc20TransactionControllerApi  # noqa: E501


class TestErc20TransactionControllerApi(unittest.TestCase):
    """Erc20TransactionControllerApi unit test stubs"""

    def setUp(self):
        self.api = Erc20TransactionControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_set_transaction_details1(self):
        """Test case for set_transaction_details1

        API to save Erc20Transaction details  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
