"""
    Yieldster SDK API

    Swagger documentation for Yieldster 2.0 SDK API's  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import YieldsterSDK.openapi_client
from YieldsterSDK.openapi_client.model.fee_model import FeeModel


class TestFeeModel(unittest.TestCase):
    """FeeModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFeeModel(self):
        """Test FeeModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FeeModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
