"""
    Yieldster SDK API

    Swagger documentation for Yieldster 2.0 SDK API's  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import YieldsterSDK.openapi_client
from YieldsterSDK.openapi_client.api.lp_controller_api import LPControllerApi  # noqa: E501


class TestLPControllerApi(unittest.TestCase):
    """LPControllerApi unit test stubs"""

    def setUp(self):
        self.api = LPControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_pool_by_asset(self):
        """Test case for get_pool_by_asset

        """
        pass


if __name__ == '__main__':
    unittest.main()
