"""
    Yieldster SDK API

    Swagger documentation for Yieldster 2.0 SDK API's  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import YieldsterSDK.openapi_client
from YieldsterSDK.openapi_client.api.api_resource_controller_api import ApiResourceControllerApi  # noqa: E501


class TestApiResourceControllerApi(unittest.TestCase):
    """ApiResourceControllerApi unit test stubs"""

    def setUp(self):
        self.api = ApiResourceControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_security_configuration(self):
        """Test case for security_configuration

        """
        pass

    def test_swagger_resources(self):
        """Test case for swagger_resources

        """
        pass

    def test_ui_configuration(self):
        """Test case for ui_configuration

        """
        pass


if __name__ == '__main__':
    unittest.main()
