"""
    Yieldster SDK API

    Swagger documentation for Yieldster 2.0 SDK API's  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import YieldsterSDK.openapi_client
from YieldsterSDK.openapi_client.api.pending_vault_transaction_controller_api import PendingVaultTransactionControllerApi  # noqa: E501


class TestPendingVaultTransactionControllerApi(unittest.TestCase):
    """PendingVaultTransactionControllerApi unit test stubs"""

    def setUp(self):
        self.api = PendingVaultTransactionControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_complete_pending_vault_transaction(self):
        """Test case for complete_pending_vault_transaction

        API to MONITOR_VAULT_CREATION  # noqa: E501
        """
        pass

    def test_create_pending_vault(self):
        """Test case for create_pending_vault

        API to CREATE PendingVaultTransaction  # noqa: E501
        """
        pass

    def test_get_all_pending_vaults(self):
        """Test case for get_all_pending_vaults

        API to get ALL_PENDING_VAULT_CREATION_TRANSACTION  # noqa: E501
        """
        pass

    def test_get_pending_vault_by_id(self):
        """Test case for get_pending_vault_by_id

        API to get PENDING_VAULT_CREATION_STATUS By ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
