"""
    Yieldster SDK API

    Swagger documentation for Yieldster 2.0 SDK API's  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import YieldsterSDK.openapi_client
from YieldsterSDK.openapi_client.model.ui_configuration import UiConfiguration


class TestUiConfiguration(unittest.TestCase):
    """UiConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUiConfiguration(self):
        """Test UiConfiguration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UiConfiguration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
