"""
    Yieldster SDK API

    Swagger documentation for Yieldster 2.0 SDK API's  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import YieldsterSDK.openapi_client
from YieldsterSDK.openapi_client.model.faq import Faq


class TestFaq(unittest.TestCase):
    """Faq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFaq(self):
        """Test Faq"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Faq()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
