"""
    Yieldster SDK API

    Swagger documentation for Yieldster 2.0 SDK API's  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import YieldsterSDK.openapi_client
from YieldsterSDK.openapi_client.model.binary import Binary
from YieldsterSDK.openapi_client.model.fee_model import FeeModel
globals()['Binary'] = Binary
globals()['FeeModel'] = FeeModel
from YieldsterSDK.openapi_client.model.pending_vault import PendingVault


class TestPendingVault(unittest.TestCase):
    """PendingVault unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPendingVault(self):
        """Test PendingVault"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PendingVault()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
