"""
    Yieldster SDK API

    Swagger documentation for Yieldster 2.0 SDK API's  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import YieldsterSDK.openapi_client
from YieldsterSDK.openapi_client.api.white_list_controller_api import WhiteListControllerApi  # noqa: E501


class TestWhiteListControllerApi(unittest.TestCase):
    """WhiteListControllerApi unit test stubs"""

    def setUp(self):
        self.api = WhiteListControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_new_white_list(self):
        """Test case for add_new_white_list

        API to add new whitelist  # noqa: E501
        """
        pass

    def test_find_by_group_id(self):
        """Test case for find_by_group_id

        Find whitelist by groupId  # noqa: E501
        """
        pass

    def test_update_white_list(self):
        """Test case for update_white_list

        Update whitelist  # noqa: E501
        """
        pass

    def test_update_whitelist_members(self):
        """Test case for update_whitelist_members

        Update members in white list  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
