"""
    Yieldster SDK API

    Swagger documentation for Yieldster 2.0 SDK API's  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import YieldsterSDK.openapi_client
from YieldsterSDK.openapi_client.api.faq_controller_api import FaqControllerApi  # noqa: E501


class TestFaqControllerApi(unittest.TestCase):
    """FaqControllerApi unit test stubs"""

    def setUp(self):
        self.api = FaqControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_faq(self):
        """Test case for add_faq

        API to add new FAQ  # noqa: E501
        """
        pass

    def test_get_all_faqs(self):
        """Test case for get_all_faqs

        API to get all FAQ  # noqa: E501
        """
        pass

    def test_update_question(self):
        """Test case for update_question

        API to update FAQ  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
