"""
    Yieldster SDK API

    Swagger documentation for Yieldster 2.0 SDK API's  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import YieldsterSDK.openapi_client
from YieldsterSDK.openapi_client.api.path_execution_service_api import PATHEXECUTIONSERVICEApi  # noqa: E501


class TestPATHEXECUTIONSERVICEApi(unittest.TestCase):
    """PATHEXECUTIONSERVICEApi unit test stubs"""

    def setUp(self):
        self.api = PATHEXECUTIONSERVICEApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_execute_path_for_test(self):
        """Test case for execute_path_for_test

        """
        pass

    def test_execute_strategy_path(self):
        """Test case for execute_strategy_path

        API to execute strategy path  # noqa: E501
        """
        pass

    def test_fetch_all_paths(self):
        """Test case for fetch_all_paths

        API to get all available execution paths  # noqa: E501
        """
        pass

    def test_find_paths(self):
        """Test case for find_paths

        API to get paths that lead us from start token to end token  # noqa: E501
        """
        pass

    def test_gas_estimator(self):
        """Test case for gas_estimator

        """
        pass

    def test_sample_erc20_token_balance(self):
        """Test case for sample_erc20_token_balance

        """
        pass

    def test_sample_function(self):
        """Test case for sample_function

        """
        pass


if __name__ == '__main__':
    unittest.main()
