"""
    Yieldster SDK API

    Swagger documentation for Yieldster 2.0 SDK API's  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import YieldsterSDK.openapi_client
from YieldsterSDK.openapi_client.api.currency_service_api import CurrencySERVICEApi  # noqa: E501


class TestCurrencySERVICEApi(unittest.TestCase):
    """CurrencySERVICEApi unit test stubs"""

    def setUp(self):
        self.api = CurrencySERVICEApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_currency(self):
        """Test case for add_currency

        API to add currency  # noqa: E501
        """
        pass

    def test_get_all_currency(self):
        """Test case for get_all_currency

        API to fetch all currency  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
